### ISSUE TITLE
Is it normal for a mod to create a load?

### ISSUE THREAD

**Issue by XionioXMaster** [nanite/ItShallNotTick#17]
### Feature Description

![image](https://user-images.githubusercontent.com/86433158/193839922-ffd76e1f-416b-4232-83b8-0072b628f01f.png)

**Comment by XionioXMaster** [comment]
https://spark.lucko.me/252KImLJ8k

**Comment by MichaelHillcox** [comment]
Just because we're in the trace does not mean we're the problem, as you can see, the complete 12.25% comes from ServerLeve.tickNonPassenger. Our mod simply defers to that call when not optimizing, meaning this is very normal. Looks like the main issues for any lag you might be having is related to minecraft entity spawning as it always is with their awful entity spawning code. 

Hope this helps.
