### ISSUE TITLE
[Server crash] 1.18.2 Skeleton

### ISSUE THREAD

**Issue by DonorKrovi** [nanite/ItShallNotTick#19]
### Mod version

ItShallNotTick-1.0.22-build.34.jar 1.18.2

### Forge mod loader version

40.1.80

### Repeatable?

- [X] Yes

### Link to log files

https://paste.gg/p/anonymous/091c4f35aa99438a9c952070a09dc710

### Steps to reproduce the issue

I don't know how to reproduce it, it happens suddenly. 
According to some reports, one of the players reported that he began to beat the skeleton and a crash occurred.

### Description of the issue you are having

idk

### Information

- [X] I have provided as much information as possible

**Comment by XionioXMaster** [comment]
Same problem

**Comment by Gaz492** [comment]
May I ask which modpack this is in?
I don't believe my mod is the cause of the problem here, it only shows up in the stack trace due to how the mod works.

If you can provide a way for me to reliably reproduce the issue then I can take a look, but without that, I'm afraid I don't have any solutions to this as it seems, a vanilla minecraft or another mods fault.

**Comment by XionioXMaster** [comment]
> 

Thanks

**Comment by Shybella** [comment]
Report: https://pastebin.com/raw/1NPruCba

This is occurring without ISNT installed.
