### ISSUE TITLE
causing server to crash

### ISSUE THREAD

**Issue by littlepianist** [nanite/ItShallNotTick#5]
### Mod version

1.0.20-build.21.jar

### Forge mod loader version

1.18.2-40.1.20

### Repeatable?

- [X] Yes

### Link to log files

[crash-2022-05-27_03.00.11-server (1).txt](https://github.com/nanite/ItShallNotTick/files/8790415/crash-2022-05-27_03.00.11-server.1.txt)

### Steps to reproduce the issue

1. hold the item thats has the same effect as totem of undying from malum mod
2. get killed by anything
3. expected to save player from death but get server crashing instead

### Description of the issue you are having

the TickOpimizer from ItShallNotTick is colliding with Malum mod's ai, casuing crash everytime activating the totem

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
I don't believe that this crash is caused by me, I'd say it's caused by the ortus mod

```
Description: Ticking entity

java.lang.IllegalArgumentException: Invalid message com.sammy.ortus.network.TotemOfUndyingEffectPacket
```

**Comment by littlepianist** [comment]
but the owner of malum said this today
![1653753291625](https://user-images.githubusercontent.com/75674050/170833039-914b0c0d-4a57-474f-9713-154b2d56e39f.jpg)

**Comment by SammySemicolon** [comment]
Sammy Here, the issue only happens when (I guess???) ISNT is instlaled, or connectivity; not sure which mod actually causes this. The ortus packet works just fine by default, so I doubt that the packet itself is the issue.

**Comment by MichaelHillcox** [comment]
This mod does not modify any packets, we simply jump into the entity ticker methods and prevent them when players are too far away. We're way to far down this trace for it to be on us. You'd be better looking at any mod that modifies the packet system. To me, it looks like the packet failed to send either because of a registry issue or some bigger issue on the packet but the trace is cause and modified by something else causing the actual issue being hidden.

I'd recommend you pull both this mod and what ever mod you feel is causing the issue onto a server and trying to reproduce the error. If you can not reproduce it, it'll show it's not our mod.

Obviously, if this ends up being us, we'll attempt to fix it but right now, looks like we're not the cause.

**Comment by SammySemicolon** [comment]
Yeah, it's more likely that it's connectivity, since that mod is all about packets.
